import { StyleSheet, Platform } from 'react-native';
import { scaleFont } from '../../utils/fontScale';
import { colors } from '../../data/dataEsqueceuSenha';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
    overflow: 'hidden',
  },
  bgCircle: {
    position: 'absolute',
    top: -120,
    right: -120,
    width: 350,
    height: 350,
    borderRadius: 175,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
    zIndex: -1,
  },
  scrollGrow: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingHorizontal: 25,
    marginBottom: 20,
  },
  back: {
    position: 'absolute',
    left: 20,
    top: 55,
    width: 45,
    height: 45,
    borderRadius: 13,
    backgroundColor: colors.glassBg,
    borderWidth: 1.5,
    borderColor: colors.glassBorder,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    elevation: 3,
    shadowColor: colors.shadowDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  backText: {
    fontSize: scaleFont(22),
    color: colors.text,
    fontWeight: '700',
  },
  headerTitle: {
    color: colors.text,
    fontSize: scaleFont(25),
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 14,
    letterSpacing: 0.4,
    lineHeight: scaleFont(30),
  },
  headerSubtitle: {
    color: colors.mutedText,
    fontSize: scaleFont(15),
    paddingHorizontal: 25,
    textAlign: 'center',
    lineHeight: scaleFont(24),
    letterSpacing: 0.2,
  },
  iconWrap: {
    marginBottom: 30,
  },
  iconRingOuter: {
    width: 135,
    height: 135,
    borderRadius: 67.5,
    backgroundColor: colors.ringOuter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconRingInner: {
    width: 115,
    height: 115,
    borderRadius: 57.5,
    backgroundColor: colors.ringInner,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCircle: {
    width: 95,
    height: 95,
    borderRadius: 47.5,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 7,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
  },
  iconEmoji: {
    fontSize: scaleFont(44),
  },
  formContent: {
    width: '100%',
    maxWidth: 360,
    alignSelf: 'center',
    paddingHorizontal: 30,
  },
  inputGroup: {
    width: '100%',
    marginBottom: 18,
  },
  label: {
    fontSize: scaleFont(14),
    fontWeight: '700',
    color: colors.text,
    marginBottom: 10,
    marginLeft: 5,
    letterSpacing: 1,
    opacity: 0.75,
  },
  checkIcon: {
    fontSize: scaleFont(21),
    color: '#1B4332',
    fontWeight: 'bold',
  },
  buttonWrap: {
    width: '100%',
    marginTop: 20,
  },
  glassButton: {
    backgroundColor: colors.glassBg,
    borderRadius: 31,
    height: 63,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.6,
    borderColor: colors.glassBorder,
    elevation: 5,
    shadowColor: colors.shadowDark,
    shadowOffset: { width: 0, height: 3.5 },
    shadowOpacity: 0.22,
    shadowRadius: 7,
  },
  buttonTitle: {
    color: '#181818',
    fontWeight: '700',
    fontSize: scaleFont(17),
    letterSpacing: 1.3,
  },
});

export default styles;
