import { StyleSheet } from 'react-native';
import { scaleFont } from '../../utils/fontScale';
import { colorsVerificar } from '../../data/dataVerificarCodigo';

export const stylesVerificar = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colorsVerificar.background,
    overflow: 'hidden',
  },
  bgCircle: {
    position: 'absolute',
    bottom: -50,
    left: -50,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    zIndex: -1,
  },
  scrollGrow: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 40,
    paddingTop: 50,
  },
  back: {
    position: 'absolute',
    left: 24,
    top: 55,
    width: 46,
    height: 46,
    borderRadius: 15,
    backgroundColor: colorsVerificar.glassBg,
    borderWidth: 1.6,
    borderColor: colorsVerificar.glassBorder,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    elevation: 3,
    shadowColor: colorsVerificar.shadowDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  backText: {
    fontSize: scaleFont(26),
    color: colorsVerificar.text,
    fontWeight: '300',
  },
  header: {
    alignItems: 'center',
    marginBottom: 40,
    width: '100%',
    paddingHorizontal: 30,
  },
  iconWrap: {
    marginBottom: 30,
  },
  iconRingOuter: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: colorsVerificar.ringOuter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconRingInner: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: colorsVerificar.ringInner,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colorsVerificar.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 7,
    shadowColor: colorsVerificar.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
  },
  iconEmoji: {
    fontSize: scaleFont(40),
  },
  headerTitle: {
    fontSize: scaleFont(25),
    fontWeight: '800',
    color: colorsVerificar.text,
    marginBottom: 13,
    letterSpacing: 0.3,
    lineHeight: scaleFont(30),
  },
  headerSubtitle: {
    fontSize: scaleFont(15),
    color: colorsVerificar.mutedText,
    textAlign: 'center',
    lineHeight: scaleFont(22),
    paddingHorizontal: 20,
  },
  highlightText: {
    color: colorsVerificar.primary,
    fontWeight: '800',
    fontSize: scaleFont(17),
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '84%',
    maxWidth: 325,
    marginBottom: 37,
    alignSelf: 'center',
  },
  otpInput: {
    width: 53,
    height: 68,
    backgroundColor: colorsVerificar.otpBackground,
    borderRadius: 13,
    textAlign: 'center',
    fontSize: scaleFont(28),
    fontWeight: '800',
    color: colorsVerificar.text,
    borderWidth: 1.3,
    borderColor: 'rgba(0,0,0,0.06)',
    shadowColor: colorsVerificar.shadowDark,
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.12,
    shadowRadius: 2.5,
    elevation: 1.5,
  },
  formContent: {
    width: '100%',
    maxWidth: 360,
    paddingHorizontal: 30,
    alignItems: 'center',
  },
  buttonWrap: {
    width: '100%',
  },
  glassButton: {
    backgroundColor: colorsVerificar.glassBg,
    borderRadius: 31,
    height: 63,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.6,
    borderColor: colorsVerificar.glassBorder,
    elevation: 5,
    shadowColor: colorsVerificar.shadowDark,
    shadowOffset: { width: 0, height: 3.5 },
    shadowOpacity: 0.22,
    shadowRadius: 7,
  },
  buttonTitle: {
    color: '#181818',
    fontWeight: '700',
    fontSize: scaleFont(17),
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  resendButton: {
    marginTop: 22,
    paddingVertical: 8,
  },
  resendText: {
    color: '#707070',
    fontSize: scaleFont(15),
    textAlign: 'center',
  },
  resendTextBold: {
    fontWeight: '800',
    color: colorsVerificar.primary,
    letterSpacing: 0.3,
  }
});
