import { StyleSheet } from 'react-native';
import { scaleFont } from '../../utils/fontScale';

export const stylesPerfil = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 100,
  },

  content: {
    paddingHorizontal: 20,
    paddingTop: 30,
    gap: 20,
  },

  settingsGear: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 10,
  },
  gearBlur: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: 'rgba(0,0,0,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },

  header: {
    alignItems: 'center',
    paddingVertical: 24,
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 24,
  },
  drakosBg: {
    position: 'absolute',
    width: 220,
    height: 220,
    opacity: 0.12,
    right: -30,
    top: -30,
    transform: [{ rotate: '-12deg' }],
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 14,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  editAvatarBtn: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#880000',
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#1a0000',
  },
  hero: {
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 16,
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 24,
    minHeight: 240,
  },
  heroWatermark: {
    position: 'absolute',
    width: 240,
    height: 240,
    opacity: 0.12,
    right: -30,
    top: -30,
    transform: [{ rotate: '-12deg' }],
  },
  heroFade: {
    ...StyleSheet.absoluteFillObject,
  },
  avatarStage: {
    position: 'relative',
    marginBottom: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarGlow: {
    position: 'absolute',
    width: 122,
    height: 122,
    borderRadius: 61,
    opacity: 0.55,
    backgroundColor: 'rgba(232,0,15,0.18)',
  },
  avatarRing: {
    width: 104,
    height: 104,
    borderRadius: 52,
    borderWidth: 2.5,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  username: {
    color: '#fff',
    fontSize: scaleFont(22),
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 10,
  },
  categoryText: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: scaleFont(13),
    textAlign: 'center',
    marginBottom: 10,
  },
  userStatus: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: scaleFont(13),
    textAlign: 'center',
  },

  // ───────────────────────────────────────────────────────────────────────
  // STATUS CHIP — identificação premium do plano (substitui "Status atual")
  // Selo glass compacto, ícone + label dinâmicos vindos de subscription.tier
  // ───────────────────────────────────────────────────────────────────────
  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 30,
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 7,
  },
  statusChipBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 30,
    borderWidth: 1,
  },
  statusChipEmoji: {
    fontSize: scaleFont(14),
  },
  statusChipText: {
    fontSize: scaleFont(12.5),
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  membershipCard: {
    borderRadius: 18,
    overflow: 'hidden',
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  membershipBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  membershipSpecularTop: {
    position: 'absolute',
    top: 0,
    left: '12%',
    right: '12%',
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.45)',
  },
  membershipTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  membershipBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    gap: 6,
  },
  membershipBadgeText: {
    fontSize: scaleFont(10.5),
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  membershipEmoji: {
    fontSize: scaleFont(24),
    marginLeft: 8,
  },
  membershipTitle: {
    color: '#fff',
    fontSize: scaleFont(18),
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  membershipSubtitle: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: scaleFont(12.5),
    marginTop: 2,
  },
  membershipDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginVertical: 12,
  },
  membershipFooterRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  membershipBenefits: {
    flex: 1,
    gap: 8,
  },
  membershipBenefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  membershipBenefitDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#e8000f',
  },
  membershipBenefitText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: scaleFont(12.5),
    fontWeight: '500',
    flex: 1,
  },
  membershipPrice: {
    color: '#fff',
    fontSize: scaleFont(15),
    fontWeight: '800',
  },
  membershipManageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    borderRadius: 12,
    overflow: 'hidden',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  membershipManageBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  membershipManageBtnText: {
    color: '#fff',
    fontSize: scaleFont(13),
    fontWeight: '700',
  },
  membershipPromo: {
    borderRadius: 18,
    overflow: 'hidden',
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    minHeight: 132,
    justifyContent: 'space-between',
  },
  membershipPromoIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(232,0,15,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(232,0,15,0.25)',
    marginBottom: 12,
  },
  membershipPromoTextGroup: {
    gap: 6,
  },
  membershipPromoTitle: {
    color: '#fff',
    fontSize: scaleFont(15.5),
    fontWeight: '800',
  },
  membershipPromoBody: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: scaleFont(12.5),
    lineHeight: scaleFont(18),
  },
  membershipPromoCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    marginTop: 14,
  },
  membershipPromoCtaText: {
    color: '#fff',
    fontSize: scaleFont(13),
    fontWeight: '800',
  },
  welcomeIconWrap: {
    alignSelf: 'flex-start',
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    backgroundColor: 'rgba(232,0,15,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(232,0,15,0.2)',
  },
  groupLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: scaleFont(12),
    fontWeight: '700',
    letterSpacing: 0.4,
    marginTop: 2,
    marginBottom: -2,
    textTransform: 'uppercase',
  },

  welcomeCard: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.05)',
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  welcomeBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  welcomeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  welcomeTitle: {
    color: '#fff',
    fontSize: scaleFont(22),
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  notifBadge: {
    position: 'relative',
    padding: 6,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  notifDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff2b2b',
    borderWidth: 1.5,
    borderColor: '#1a0000',
  },
  welcomeBody: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: scaleFont(14),
    lineHeight: scaleFont(22),
    marginBottom: 14,
  },

  subBadge: {
    borderRadius: 30,
    overflow: 'hidden',
    marginBottom: 0,
  },
  subBadgeBlur: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(255,215,0,0.25)',
    backgroundColor: 'rgba(255,215,0,0.08)',
    gap: 8,
  },
  subBadgeText: {
    color: '#800000',
    fontSize: scaleFont(13),
    fontWeight: '700',
  },
  subBadgePrice: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: scaleFont(11),
    fontWeight: '600',
  },

  // ───────────────────────────────────────────────────────────────────────
  // PLAN PANEL — painel funcional dentro do card "Seja bem-vindo"
  // Dois estados: sócio (plano + benefícios + status) e não-sócio (incentivo)
  // ───────────────────────────────────────────────────────────────────────
  planPanel: {
    borderRadius: 14,
    overflow: 'hidden',
    padding: 14,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  planPanelBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
  },
  planPanelHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  planPanelHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 10,
  },
  planPanelEmoji: {
    fontSize: scaleFont(26),
  },
  planPanelTitle: {
    color: '#fff',
    fontSize: scaleFont(16),
    fontWeight: '800',
    letterSpacing: 0.1,
  },
  planPanelStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 3,
  },
  planPanelStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4ee08a',
  },
  planPanelStatusText: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: scaleFont(11.5),
    fontWeight: '600',
  },
  planPanelPrice: {
    color: '#fff',
    fontSize: scaleFont(15),
    fontWeight: '800',
  },
  planPanelDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginVertical: 12,
  },
  planPanelBenefits: {
    gap: 8,
    marginBottom: 14,
  },
  planPanelBenefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  planPanelBenefitText: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: scaleFont(12.5),
    fontWeight: '500',
    flex: 1,
  },
  planPanelManageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    gap: 6,
  },
  planPanelManageBtnText: {
    color: '#fff',
    fontSize: scaleFont(13),
    fontWeight: '700',
  },
  planPanelPromoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  planPanelPromoTitle: {
    color: '#fff',
    fontSize: scaleFont(15.5),
    fontWeight: '800',
  },
  planPanelPromoBody: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: scaleFont(12.5),
    lineHeight: scaleFont(18),
    fontWeight: '400',
    marginBottom: 14,
  },
  planPanelCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 42,
    borderRadius: 12,
    overflow: 'hidden',
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  planPanelCtaText: {
    color: '#fff',
    fontSize: scaleFont(13.5),
    fontWeight: '800',
    letterSpacing: 0.2,
  },

  actionsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  actionCard: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingVertical: 16,
    paddingHorizontal: 8,
    minHeight: 90,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  actionBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  actionIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  actionContent: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  actionLabel: {
    color: '#fff',
    fontSize: scaleFont(12),
    fontWeight: '500',
    textAlign: 'center',
  },

  sectionHeaderCustom: {
    marginBottom: 4,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#fff',
    fontSize: scaleFont(18),
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  sectionEditBtn: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },

  infoCard: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  infoBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  infoIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  infoLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  infoTextGroup: {
    marginLeft: 14,
    flex: 1,
  },
  infoLabel: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: scaleFont(12),
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  infoValue: {
    color: '#fff',
    fontSize: scaleFont(16),
    fontWeight: '600',
  },
  infoDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginHorizontal: 18,
  },

  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    paddingVertical: 16,
    marginTop: 12,
    gap: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,100,100,0.3)',
  },
  logoutBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,100,100,0.2)',
  },
  logoutText: {
    color: '#ff6b6b',
    fontSize: scaleFont(16),
    fontWeight: '600',
    letterSpacing: 0.5,
  },

  historySection: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.05)',
    marginTop: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    padding: 16,
  },
  historyBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  historyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  historyCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  historyTitle: {
    color: '#fff',
    fontSize: scaleFont(17),
    fontWeight: '700',
  },
  historySubBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,215,0,0.12)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,215,0,0.25)',
    marginBottom: 14,
    gap: 8,
  },
  historySubEmoji: {
    fontSize: scaleFont(13),
  },
  historySubText: {
    color: '#ffd700',
    fontSize: scaleFont(13),
    fontWeight: '600',
    flex: 1,
  },
  historySubPrice: {
    color: '#ffd700',
    fontSize: scaleFont(13),
    fontWeight: '700',
  },
  historyListTitle: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: scaleFont(13),
    fontWeight: '600',
    marginBottom: 8,
    letterSpacing: 0.4,
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  historyIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  historyInfo: {
    flex: 1,
    marginLeft: 10,
  },
  historyPlan: {
    color: '#fff',
    fontSize: scaleFont(14),
    fontWeight: '600',
  },
  historyDate: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: scaleFont(11),
    marginTop: 1,
  },
  historyPrice: {
    color: '#fff',
    fontSize: scaleFont(14),
    fontWeight: '700',
  },
  historyDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginVertical: 2,
  },
  historyProductImage: {
    width: 36,
    height: 36,
    borderRadius: 8,
    marginRight: 8,
  },
  historyEmpty: {
    alignItems: 'center',
    paddingVertical: 24,
    gap: 8,
  },
  historyEmptyText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: scaleFont(13),
    textAlign: 'center',
  },

  modalTitle: {
    fontSize: scaleFont(24),
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 20,
    textAlign: 'center',
  },
  modalField: {
    marginBottom: 16,
  },
  modalLabel: {
    fontSize: scaleFont(14),
    color: '#555',
    marginBottom: 6,
    fontWeight: '600',
  },
  modalInput: {
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: scaleFont(15),
    color: '#000',
    borderWidth: 1,
    borderColor: '#ddd',
  },
});
