import { StyleSheet, Platform } from 'react-native';
import { scaleFont } from '../../utils/fontScale';
import { theme } from '../../data/dataCarrinhos';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.background },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 15 },
  headerTitle: { fontSize: scaleFont(16), fontWeight: '800', color: theme.black, letterSpacing: 1 },
  backButton: { width: 40, height: 40, justifyContent: 'center' },
  clearText: { color: theme.accent, fontWeight: '600', fontSize: scaleFont(14) },
  clearTextDisabled: { opacity: 0 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 150 },
  emptyScrollContent: { flexGrow: 1, justifyContent: 'center' },
  cartItemContainer: { marginBottom: 15 },
  cartItem: { flexDirection: 'row', backgroundColor: theme.surface, borderRadius: 24, padding: 12, ...Platform.select({ ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 10 }, android: { elevation: 3 } }) },
  imageWrapper: { width: 90, height: 110, borderRadius: 18, backgroundColor: '#F2F2F7', overflow: 'hidden' },
  productImage: { width: '100%', height: '100%' },
  imagePlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  infoContainer: { flex: 1, marginLeft: 15, justifyContent: 'space-between', paddingVertical: 2 },
  sectionLabel: { fontSize: scaleFont(10), fontWeight: '700', color: theme.accent, textTransform: 'uppercase', marginBottom: 4 },
  productName: { fontSize: scaleFont(16), fontWeight: '700', color: theme.text, marginBottom: 8, lineHeight: scaleFont(20) },
  detailsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  detailText: { fontSize: scaleFont(12), color: theme.textSecondary, fontWeight: '500' },
  detailValue: { fontWeight: '700', color: theme.black },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  priceLabel: { fontSize: scaleFont(12), color: theme.textSecondary, fontWeight: '500' },
  priceValue: { fontSize: scaleFont(15), fontWeight: '700', color: theme.black },
  actionsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  quantityControls: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F2F2F7', borderRadius: 12, padding: 4 },
  qtyBtn: { width: 30, height: 30, justifyContent: 'center', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 8 },
  qtyBtnDisabled: { opacity: 0.5 },
  qtySymbol: { fontSize: scaleFont(18), fontWeight: '600' },
  qtyNumber: { fontSize: scaleFont(14), fontWeight: '800', marginHorizontal: 12, minWidth: 28, textAlign: 'center' },
  deleteButton: { width: 38, height: 38, borderRadius: 12, backgroundColor: theme.accentLight, justifyContent: 'center', alignItems: 'center' },
  bottomBarContainer: { position: 'absolute', bottom: 30, left: 20, right: 20 },
  bottomBar: { backgroundColor: 'rgba(255, 255, 255, 0.95)', borderRadius: 30, padding: 15, paddingLeft: 25, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 20, elevation: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.5)' },
  totalLabel: { fontSize: scaleFont(12), color: theme.textSecondary, fontWeight: '600' },
  totalAmount: { fontSize: scaleFont(24), fontWeight: '900', color: theme.black, letterSpacing: -0.5 },
  checkoutButton: { backgroundColor: theme.black, flexDirection: 'row', height: 54, paddingLeft: 20, paddingRight: 6, borderRadius: 22, alignItems: 'center' },
  checkoutText: { color: '#FFF', fontWeight: '700', fontSize: scaleFont(15), marginRight: 12 },
  checkoutIcon: { width: 42, height: 42, backgroundColor: '#FFF', borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  emptyState: { alignItems: 'center', paddingHorizontal: 40 },
  emptyIconCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: theme.accentLight, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
  emptyTitle: { fontSize: scaleFont(20), fontWeight: '800', color: theme.text, marginBottom: 8 },
  emptySubtitle: { fontSize: scaleFont(14), color: theme.textSecondary, textAlign: 'center', marginBottom: 30 },
  shopButton: { backgroundColor: theme.black, paddingVertical: 14, paddingHorizontal: 30, borderRadius: 18 },
  shopButtonText: { color: '#FFF', fontWeight: '700' },
});

export default styles;
