import { StyleSheet } from 'react-native';
import { scaleFont } from '../../utils/fontScale';
import { colorsNovaSenha } from '../../data/dataNovaSenha';

export const stylesNovaSenha = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colorsNovaSenha.background,
    overflow: 'hidden',
  },
  bgCircle: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    zIndex: -1,
  },
  scrollGrow: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 40,
    paddingTop: 50,
  },
  back: {
    position: 'absolute',
    left: 20,
    top: 55,
    width: 46,
    height: 46,
    borderRadius: 15,
    backgroundColor: colorsNovaSenha.glassBg,
    borderWidth: 1.5,
    borderColor: colorsNovaSenha.glassBorder,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    elevation: 3,
    shadowColor: colorsNovaSenha.shadowDark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  backText: {
    fontSize: scaleFont(26),
    color: colorsNovaSenha.text,
    fontWeight: '300',
  },
  header: {
    alignItems: 'center',
    marginBottom: 40,
    width: '100%',
    paddingHorizontal: 35,
  },
  iconWrap: {
    marginBottom: 30,
  },
  iconRingOuter: {
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: colorsNovaSenha.ringOuter,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconRingInner: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: colorsNovaSenha.ringInner,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: colorsNovaSenha.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 7,
    shadowColor: colorsNovaSenha.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
  },
  iconEmoji: {
    fontSize: scaleFont(40),
  },
  headerTitle: {
    fontSize: scaleFont(29),
    fontWeight: '800',
    color: colorsNovaSenha.text,
    marginBottom: 12,
    letterSpacing: 0.3,
    lineHeight: scaleFont(35),
  },
  headerSubtitle: {
    fontSize: scaleFont(16),
    color: colorsNovaSenha.mutedText,
    textAlign: 'center',
    paddingHorizontal: 25,
    lineHeight: scaleFont(22),
    letterSpacing: 0.1,
  },
  formContent: {
    width: '100%',
    maxWidth: 400,
    paddingHorizontal: 31,
  },
  inputGroup: {
    marginBottom: 22,
    width: '100%',
  },
  label: {
    fontSize: scaleFont(14),
    fontWeight: '700',
    color: colorsNovaSenha.text,
    marginBottom: 10,
    marginLeft: 5,
    letterSpacing: 0.8,
    opacity: 0.85,
  },
  checkIcon: {
    fontSize: scaleFont(18),
    color: colorsNovaSenha.accent,
    fontWeight: 'bold',
    marginRight: 10,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  buttonWrap: {
    marginTop: 20,
  },
  glassButton: {
    backgroundColor: colorsNovaSenha.glassBg,
    borderRadius: 31,
    height: 63,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.6,
    borderColor: colorsNovaSenha.glassBorder,
    elevation: 5,
    shadowColor: colorsNovaSenha.shadowDark,
    shadowOffset: { width: 0, height: 3.5 },
    shadowOpacity: 0.22,
    shadowRadius: 7,
  },
  buttonTitle: {
    color: '#181818',
    fontWeight: '700',
    fontSize: scaleFont(17),
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
});
